### ISSUE TITLE
[BUG] Exception: Unable to instantiate receiver com.lizongying.mytv0.BootReceiver: java.lang.ClassCastException: com.lizongying.mytv0.LocaleContextWrapper cannot be cast to android.app.ContextImpl

### ISSUE THREAD

**Issue by lizongying** [lizongying/my-tv-0#103]
### 提問題前請檢查

- [X] 已檢查過問題列表，沒有人提過相同問題
- [X] 軟件的最新版本依然沒有被修復

### 軟件版本

-

### 電視品牌

-

### Android版本

-

### 問題描述

1. 這是一個崩潰日誌，應該涉及所有版本、設備，頻率比較高。自己尚未發現。
2. 沒有找到解決辦法，特此求助大家。
3. 詳細錯誤
Exception: Unable to instantiate receiver com.lizongying.mytv0.BootReceiver: java.lang.ClassCastException: com.lizongying.mytv0.LocaleContextWrapper cannot be cast to android.app.ContextImpl
StackTrace: java.lang.RuntimeException: Unable to instantiate receiver com.lizongying.mytv0.BootReceiver: java.lang.ClassCastException: com.lizongying.mytv0.LocaleContextWrapper cannot be cast to android.app.ContextImpl
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4435)
	at android.app.ActivityThread.access$1600(ActivityThread.java:260)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2143)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:8060)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1091)
Caused by: java.lang.ClassCastException: com.lizongying.mytv0.LocaleContextWrapper cannot be cast to android.app.ContextImpl
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4413)
	... 9 more

**Comment by vrichv** [comment]
这个在kitkat上应该是必现的

**Comment by lizongying** [comment]
已處理
