### ISSUE TITLE
[BUG] 先切换频道 > 再切换APP到后台 > 再恢复APP时 概率崩溃问题

### ISSUE THREAD

**Issue by dyccsxg** [lizongying/my-tv-0#18]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### 我的电视·〇 版本

v1.0.1

### Bug 描述

先切换频道 > 再切换APP到后台 > 再恢复APP时 概率崩溃问题

### 预期行为

APP不崩溃，可正常播放

### 实际行为

FATAL EXCEPTION: main
Process: com.lizongying.mytv0, PID: 6928
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at androidx.fragment.app.FragmentManagerImpl.checkStateLoss(FragmentManagerImpl.java:1536)
	at androidx.fragment.app.FragmentManagerImpl.enqueueAction(FragmentManagerImpl.java:1558)
	at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:317)
	at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:282)
	at com.lizongying.mytv0.MainActivity.hideMenu$lambda$3(MainActivity.kt:244)
	at com.lizongying.mytv0.MainActivity.$r8$lambda$_VPCsEo9uM-vY0gaD8kyoi0HVUA(Unknown Source:0)
	at com.lizongying.mytv0.MainActivity$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
  Force finishing activity com.lizongying.mytv0/.MainActivity

### 复现步骤

先切换频道 > 再切换APP到后台 > 再恢复APP时 概率崩溃问题

### UI / OS

华为

### Android 版本

HarmonyOS 2.0

**Comment by lizongying** [comment]
[1.0.8](https://github.com/lizongying/my-tv-0/tree/v1.0.8) 已解决
