### ISSUE TITLE
[BUG] 刚启动的时候遇到闪退npe

### ISSUE THREAD

**Issue by shuohao** [lizongying/my-tv-0#60]
### 检查清单

- [X] 之前没有人提交过类似或相同的 bug report。
- [X] 我正在使用本软件的最新版本。

### 我的电视·〇 版本

最新

### Bug 描述

java.lang.NullPointerException
	at com.lizongying.mytv0.ErrorFragment.getBinding(ErrorFragment.kt:13)
	at com.lizongying.mytv0.ErrorFragment.show(ErrorFragment.kt:37)
	at com.lizongying.mytv0.MainActivity.hideErrorFragment(MainActivity.kt:524)
	at com.lizongying.mytv0.MainActivity.access$hideErrorFragment(MainActivity.kt:25)
	at com.lizongying.mytv0.MainActivity$watch$1$2.invoke(MainActivity.kt:196)
	at com.lizongying.mytv0.MainActivity$watch$1$2.invoke(MainActivity.kt:189)
	at com.lizongying.mytv0.MainActivity$sam$androidx_lifecycle_Observer$0.onChanged(Unknown Source:2)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
	at com.lizongying.mytv0.models.TVModel.setReady(TVModel.kt:84)
	at com.lizongying.mytv0.models.TVList.setPosition(TVList.kt:340)
	at com.lizongying.mytv0.MainActivity.ready(MainActivity.kt:149)
	at com.lizongying.mytv0.PlayerFragment$onCreateView$1.onGlobalLayout(PlayerFragment.kt:136)
	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1142)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4167)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2933)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10235)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1634)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1643)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1172)
	at android.view.Choreographer.doFrame(Choreographer.java:1076)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1607)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

### 预期行为

正常

### 实际行为

闪退

### UI / OS

小米

### Android 版本

14

**Comment by lizongying** [comment]
1.2.8已修復
